version: '3.6'
services:
  postgres:
    image: postgres:latest
    ports: 
      - 5432:5432
    restart: always
    volumes:
    - ../data/postgresql:/var/lib/postgresql/data
    # - 'db_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    # networks:
    #   - webnet
  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
    - "8083:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:123456@postgres:5432/postgres
      PG_DATABASE_URL: postgres://postgres:123456@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: quynguyen
    # networks:
    #   - webnet
# networks:
#   webnet:
# volumes:
#   db_data:
# pgloader mysql://web2mobile:EApRtAYQBHrduzh3tSdniwLr@database.wehelp.vn:3306/web2mobile_dev postgres://postgres:123456@51.79.140.20:5432/postgres
